% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.2a (COMSOL 3.2.0.300, $Date: 2005/12/20 19:02:30 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.2';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 300;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2005/12/20 19:02:30 $';
fem.version = vrsn;

% Geometry
g1=rect2(1.4,1,'base','corner','pos',[-0.8,-0.8]);
carr={curve2([-0.8,-0.8],[0,-0.4],[1,1])};
g2=geomcoerce('curve',carr);
g3=geomcoerce('solid',{g1,g2});
gg=geomedit(g3);
gg([3])={[]};
gg{1}=beziercurve2([-0.8,-0.8],[-0.8,0],[1,1]);
g4=geomedit(g3,gg);
carr={curve2([-0.6,-0.4,-0.2,0],[-0.2,0,-0.2,-0.4],[1,1,1,1]), ...
  curve2([0,-0.6],[-0.4,-0.2],[1,1])};
g5=geomcoerce('solid',carr);
carr={curve2([-0.2,0],[-0.4,-0.2],[1,1])};
g6=geomcoerce('curve',carr);
g7=geomcoerce('solid',{g5,g6});
g8=geomcoerce('solid',{g4,g7});
gg=geomedit(g8);
gg([6])={[]};
g9=geomedit(g8,gg);
gg=geomedit(g9);
gg([9])={[]};
gg{8}=beziercurve2([-0.6,-0.433650880356206,-0.267301760712411,0],[-0.2,-0.0336508803562055,-0.144022056775066,-0.4],[1,1,1,1]);
g10=geomedit(g9,gg);
clear s
s.objs={g10};
s.name={'CO2'};
s.tags={'g10'};

fem.draw=struct('s',s);

% (Default values are not included)
fem.sdim = {'x','y'};
fem.frame = {'ref'};
fem.border = 1;
fem.units = 'SI';

% Multiphysics
fem=multiphysics(fem);

% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.2a (COMSOL 3.2.0.300, $Date: 2005/12/20 19:02:30 $)

% Geometry
clear s
s.objs={g10};
s.name={'CO2'};
s.tags={'g10'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);

% Initialize mesh
fem.mesh=meshinit(fem);

% (Default values are not included)
fem.frame = {'ref'};
fem.border = 1;
fem.units = 'SI';

% Multiphysics
fem=multiphysics(fem);
